server:
  port: 8060
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/rohan/Documents/GitHub/SpringCloudCourse/config/config
